owner: classtinginc
repo: upptime
user-agent: KojBot
sites:
  - name: Classting Web
    url: https://www.classting.com/nginx_status
  - name: Classting API
    url: https://ctapi.classting.com/health_checks
  - name: Classting AD
    url: https://adapi.classting.com/health_checks
  - name: Classting AI
    url: https://clapi.classting.com/health_checks
  - name: Classroom
    url: https://newclass.classting.com
# notifications:
#   - type: slack
#     channel: C016QTU9S9Y
assignees:
  - junheon
status-website:
  cname: upptime.classting.com
  logoUrl: https://about.classting.com//images/ct_company_nav_logo.png
  name: Classting upptime
  introTitle: "**Upptime** for Classting"
  introMessage: Classting을 구성하는 서비스의 Upptime
